// <auto-generated />
namespace BiblioCat.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EmailToPatreon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailToPatreon));
        
        string IMigrationMetadata.Id
        {
            get { return "202104201500121_EmailToPatreon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
